### ISSUE TITLE
在Android13上安装失败

### ISSUE THREAD

**Issue by feilongproject** [andywu91/XAPKInstaller#6]
看起来似乎是因为权限原因，不过apkpure能成功安装，很奇怪

logcat：
```
2023-09-01 12:26:11.186 17306-17306 System.err              com.wuliang.xapkinstaller            W  org.zeroturnaround.zip.ZipException: Failed to process zip entry 'Android/obb/com.YostarJP.BlueArchive/main.231115.com.YostarJP.BlueArchive.obb' with action org.zeroturnaround.zip.ZipUtil$Unpacker@1c17854
2023-09-01 12:26:11.187 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:511)
2023-09-01 12:26:11.187 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472)
2023-09-01 12:26:11.190 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:996)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.wuliang.lib.XapkInstallerFactoryKt.unzipObbToAndroidObbDir(XapkInstallerFactory.kt:77)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.wuliang.lib.XapkInstallerFactoryKt.createXapkInstaller(XapkInstallerFactory.kt:50)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.wuliang.xapkinstaller.MainActivity.doInstall(MainActivity.kt:184)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.wuliang.xapkinstaller.MainActivity.downloadXapkAndInstall(MainActivity.kt:128)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.wuliang.xapkinstaller.MainActivity.install(MainActivity.kt:113)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.wuliang.xapkinstaller.MainActivity.checkAndInstall(MainActivity.kt:51)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.wuliang.xapkinstaller.MainActivity.access$checkAndInstall(MainActivity.kt:33)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.wuliang.xapkinstaller.MainActivity$onCreate$1.onClick(MainActivity.kt:40)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at android.view.View.performClick(View.java:7506)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at android.view.View.performClickInternal(View.java:7483)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at android.view.View$PerformClick.run(View.java:29334)
2023-09-01 12:26:11.191 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at android.os.Handler.handleCallback(Handler.java:942)
2023-09-01 12:26:11.192 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at android.os.Handler.dispatchMessage(Handler.java:99)
2023-09-01 12:26:11.192 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at android.os.Looper.loopOnce(Looper.java:201)
2023-09-01 12:26:11.192 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at android.os.Looper.loop(Looper.java:288)
2023-09-01 12:26:11.192 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at android.app.ActivityThread.main(ActivityThread.java:7872)
2023-09-01 12:26:11.192 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at java.lang.reflect.Method.invoke(Native Method)
2023-09-01 12:26:11.192 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2023-09-01 12:26:11.192 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-09-01 12:26:11.195 17306-17306 System.err              com.wuliang.xapkinstaller            W  Caused by: java.io.IOException: Unable to create directory /storage/emulated/0/Android/obb/com.YostarJP.BlueArchive
2023-09-01 12:26:11.195 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at org.zeroturnaround.zip.commons.FileUtilsV2_2.forceMkdir(FileUtilsV2_2.java:898)
2023-09-01 12:26:11.196 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at org.zeroturnaround.zip.ZipUtil$Unpacker.process(ZipUtil.java:1166)
2023-09-01 12:26:11.196 17306-17306 System.err              com.wuliang.xapkinstaller            W  	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:508)
2023-09-01 12:26:11.196 17306-17306 System.err              com.wuliang.xapkinstaller            W  	... 22 more
```

**Comment by andywu91** [comment]
目录创建失败，是不是你们项目targetSdk升到30，但没有适配新的沙箱存储，我这边也测试一下

**Comment by feilongproject** [comment]
找到问题了，在安卓8版本以上只需要申请 `ACTION_MANAGE_UNKNOWN_APP_SOURCES` 权限就可以直接对 `Android/obb` 进行操作了，我这边项目已经上线了
https://github.com/feilongproject/BAAssetsDownloader/blob/8106f193621dba7cf87fccbaf2d6b81b11e1a869/app/src/main/java/com/feilongproject/baassetsdownloader/util/permission.kt#L18

**Comment by andywu91** [comment]
感谢说明
